raw_path: P:\path\to\your\raw\data\folder
stage_path: P:\path\to\your\stage\folder

databanks:
  postgres:
    db_uri: "postgresql://username:password@localhost:5432/postgres"
    set_name:
      dataset: 'delta_froms'
      table_name: 'lorem_ipsum'
      if_exists: 'replace' # I utilize 'replace' as default, but it could be 'append' or 'fail
      chunksize: '10000' # Useful for large files